name: POC

on:
  push:
    branches:    
      - main
    
env:
  TAG: main
    
jobs:
  poc:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
          
      - name: Install Artifactory
        run: |
          wget -O artifactory-pro.deb "https://releases.jfrog.io/artifactory/artifactory-pro-debs/pool/jfrog-artifactory-pro/jfrog-artifactory-pro-[RELEASE].deb"
          sudo apt install ./artifactory-pro.deb -y
          sudo systemctl start artifactory.service
          
          
      - name: Install XRay
        run: |
          sudo apt update
          sudo apt install db-util
          
          # sync package metadata
          sudo apt-get update
          # install dependencies manually
          sudo apt-get -y install socat logrotate init-system-helpers adduser

          # download the package
          sudo apt-get -y install wget
          wget https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.10.1/rabbitmq-server_3.10.1-1_all.deb

          # install the package with dpkg
          sudo dpkg -i rabbitmq-server_3.10.1-1_all.deb

          rm rabbitmq-server_3.10.1-1_all.deb

          wget -O xray-ubuntu-latest.tar.gz https://releases.jfrog.io/artifactory/jfrog-xray/xray-linux/[RELEASE]/jfrog-xray-[RELEASE]-linux.tar.gz?_gl=1*npua3y*_ga*ODQzODQ5OTI0LjE2NTI0Nzg0MTM.*_ga_SQ1NR9VTFJ*MTY1MjQ3ODQxMC4xLjEuMTY1MjQ4MTcyOS4xNg..
          cd /home/runner/work/POC/POC
          tar -xzf xray-ubuntu-latest.tar.gz
          cd jfrog-xray-3.48.2-linux
          cd app/bin
          ls
          sudo bash xray.sh start
          
      - name: Install JFrog CLI
        run: |
          npm install -g jfrog-cli-v2-jf
          jf --version
          
      - name: Scan
        run: |
          jf scan "/home/runner/work/POC/POC/poc.sql"
          
      
      
          
        
    
        
        
          
