name: POC

on:
  push:
    branches:    
      - main
    
env:
  TAG: main
    
jobs:
  poc:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
          
      - name: Install XRay
        run: |
          wget -O xray-ubuntu-latest.tar.gz https://releases.jfrog.io/artifactory/jfrog-xray/xray-linux/[RELEASE]/jfrog-xray-[RELEASE]-linux.tar.gz?_gl=1*npua3y*_ga*ODQzODQ5OTI0LjE2NTI0Nzg0MTM.*_ga_SQ1NR9VTFJ*MTY1MjQ3ODQxMC4xLjEuMTY1MjQ4MTcyOS4xNg..
          cd /home/runner/work/POC/POC
          mkdir /opt/jfrog
          mv xray-ubuntu-latest.tar.gz /opt/jfrog
          cd /opt/jfrog
          tar -xzf xray-ubuntu-latest.tar.gz
          cd jfrog-xray-3.48.2-linux
          cd app/bin
          ls
          sudo bash xray.sh start
    
        
        
          
