name: POC

on:
  push:
    branches:    
      - main
    
env:
  TAG: main
    
jobs:
  poc:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
        
          
      - name: Install JFrog CLI
        run: |
          npm install -g jfrog-cli-v2-jf
          jf --version
          
      - name: Scan
        run: |
          jf scan "/home/runner/work/POC/POC/poc.sql"
          
      
      
          
        
    
        
        
          
