name: POC

on:
  push:
    branches:    
      - main
    
env:
  TAG: POC
    
jobs:
  poc:
    runs-on: [ubuntu-latest]
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           ref: {{ env.TAG }}
          
      - name: Install XRay
        run: |
          tar -xzf xray-ubuntu-latest.tar.gz
          ./installXray-ubuntu.sh --use-defaults
          
